# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usdExportUI.ui'
#
# Created: Wed Nov 14 14:48:08 2018
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(900, 731)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_11 = QtWidgets.QGridLayout(Form)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet(_fromUtf8("background-color: rgb(62, 115, 186);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
""))
        self.title_label.setScaledContents(False)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.gridLayout_11.addWidget(self.title_label, 0, 1, 1, 2)
        self.titleLogo_label = QtWidgets.QLabel(Form)
        self.titleLogo_label.setMaximumSize(QtCore.QSize(60, 70))
        self.titleLogo_label.setStyleSheet(_fromUtf8("background-color: rgb(62, 115, 186);\n"
"padding:  0 0 0 20 px;"))
        self.titleLogo_label.setText(_fromUtf8(""))
        self.titleLogo_label.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../../../../../../../../home/jungmin.leer/.designer/resources/alembic_white.png")))
        self.titleLogo_label.setObjectName(_fromUtf8("titleLogo_label"))
        self.gridLayout_11.addWidget(self.titleLogo_label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(900, 0))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(80, 80, 80);"))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.userName_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userName_label.setFont(font)
        self.userName_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255); padding: 10 5 0 0 px;"))
        self.userName_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.userName_label.setObjectName(_fromUtf8("userName_label"))
        self.gridLayout_14.addWidget(self.userName_label, 0, 2, 1, 1)
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame1.setLineWidth(2)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setMargin(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.outDir_lineEdit = QtWidgets.QLineEdit(self.frame1)
        self.outDir_lineEdit.setAutoFillBackground(False)
        self.outDir_lineEdit.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(100,100,100);"))
        self.outDir_lineEdit.setObjectName(_fromUtf8("outDir_lineEdit"))
        self.gridLayout_2.addWidget(self.outDir_lineEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color : white;"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.openOutDir_pushButton = QtWidgets.QPushButton(self.frame1)
        self.openOutDir_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.openOutDir_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.openOutDir_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(100, 100, 100);"))
        self.openOutDir_pushButton.setText(_fromUtf8(""))
        self.openOutDir_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.openOutDir_pushButton.setObjectName(_fromUtf8("openOutDir_pushButton"))
        self.gridLayout_2.addWidget(self.openOutDir_pushButton, 2, 3, 1, 1)
        self.openExportFile_pushButton = QtWidgets.QPushButton(self.frame1)
        self.openExportFile_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.openExportFile_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.openExportFile_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(100, 100, 100);"))
        self.openExportFile_pushButton.setText(_fromUtf8(""))
        self.openExportFile_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.openExportFile_pushButton.setObjectName(_fromUtf8("openExportFile_pushButton"))
        self.gridLayout_2.addWidget(self.openExportFile_pushButton, 0, 3, 1, 1)
        self.findExportFile_pushButton = QtWidgets.QPushButton(self.frame1)
        self.findExportFile_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.findExportFile_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.findExportFile_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);"))
        self.findExportFile_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.findExportFile_pushButton.setObjectName(_fromUtf8("findExportFile_pushButton"))
        self.gridLayout_2.addWidget(self.findExportFile_pushButton, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color : white;"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.findOutDir_pushButton = QtWidgets.QPushButton(self.frame1)
        self.findOutDir_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.findOutDir_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.findOutDir_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(100, 100, 100);\n"
"color: rgb(255, 255, 255);"))
        self.findOutDir_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.findOutDir_pushButton.setObjectName(_fromUtf8("findOutDir_pushButton"))
        self.gridLayout_2.addWidget(self.findOutDir_pushButton, 2, 2, 1, 1)
        self.exportFile_lineEdit = QtWidgets.QLineEdit(self.frame1)
        self.exportFile_lineEdit.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(100,100,100);"))
        self.exportFile_lineEdit.setObjectName(_fromUtf8("exportFile_lineEdit"))
        self.gridLayout_2.addWidget(self.exportFile_lineEdit, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame1, 1, 0, 1, 3)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(10, -1, -1, -1)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color : white;"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 0, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(self.frame)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 0, 1, 1)
        self.machineType_comboBox = QtWidgets.QComboBox(self.frame2)
        self.machineType_comboBox.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.machineType_comboBox.setFont(font)
        self.machineType_comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.machineType_comboBox.setAccessibleDescription(_fromUtf8(""))
        self.machineType_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.machineType_comboBox.setAutoFillBackground(False)
        self.machineType_comboBox.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(90,90,90);\n"
"padding : 0 5 0 5 px;"))
        self.machineType_comboBox.setObjectName(_fromUtf8("machineType_comboBox"))
        self.machineType_comboBox.addItem(_fromUtf8(""))
        self.machineType_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.machineType_comboBox, 0, 1, 1, 1)
        self.doExport_pushButton = QtWidgets.QPushButton(self.frame2)
        self.doExport_pushButton.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.doExport_pushButton.setFont(font)
        self.doExport_pushButton.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(62, 109, 186);"))
        self.doExport_pushButton.setObjectName(_fromUtf8("doExport_pushButton"))
        self.gridLayout_6.addWidget(self.doExport_pushButton, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.frame3 = QtWidgets.QFrame(self.frame2)
        self.frame3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame3.setObjectName(_fromUtf8("frame3"))
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 4, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.frame3)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setStyleSheet(_fromUtf8(""))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(-1, 2, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.rigVersionUp_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.rigVersionUp_checkBox.setMinimumSize(QtCore.QSize(130, 0))
        self.rigVersionUp_checkBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rigVersionUp_checkBox.setFont(font)
        self.rigVersionUp_checkBox.setToolTip(_fromUtf8(""))
        self.rigVersionUp_checkBox.setAutoFillBackground(False)
        self.rigVersionUp_checkBox.setStyleSheet(_fromUtf8("color : white;"))
        self.rigVersionUp_checkBox.setObjectName(_fromUtf8("rigVersionUp"))
        self.verticalLayout_4.addWidget(self.rigVersionUp_checkBox)
        self.groom_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.groom_checkBox.setStyleSheet(_fromUtf8("color : white;"))
        self.groom_checkBox.setObjectName(_fromUtf8("groom_checkBox"))
        self.verticalLayout_4.addWidget(self.groom_checkBox)
        self.only_groom_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.only_groom_checkBox.setStyleSheet(_fromUtf8("color : white;"))
        self.only_groom_checkBox.setObjectName(_fromUtf8("only_groom_checkBox"))
        self.verticalLayout_4.addWidget(self.only_groom_checkBox)
        self.dontParallelCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.dontParallelCheckBox.setStyleSheet(_fromUtf8("color : white;"))
        self.dontParallelCheckBox.setObjectName(_fromUtf8("dontParallelCheckBox"))
        self.verticalLayout_4.addWidget(self.dontParallelCheckBox)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.only_bake_checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.only_bake_checkBox.setStyleSheet(_fromUtf8("color : white;"))
        self.only_bake_checkBox.setObjectName(_fromUtf8("only_bake_checkBox"))
        self.verticalLayout_4.addWidget(self.only_bake_checkBox)
        self.gridLayout_8.addWidget(self.frame_2, 2, 0, 2, 2)
        self.frame4 = QtWidgets.QFrame(self.frame3)
        self.frame4.setObjectName(_fromUtf8("frame4"))
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame4)
        self.gridLayout_12.setContentsMargins(-1, 0, -1, 2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_10 = QtWidgets.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_12.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.stepFrame_lineEdit = QtWidgets.QLineEdit(self.frame4)
        self.stepFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.stepFrame_lineEdit.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stepFrame_lineEdit.setFont(font)
        self.stepFrame_lineEdit.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(100,100,100);"))
        self.stepFrame_lineEdit.setObjectName(_fromUtf8("stepFrame_lineEdit"))
        self.gridLayout_3.addWidget(self.stepFrame_lineEdit, 1, 2, 1, 1)
        self.startFrame_lineEdit = QtWidgets.QLineEdit(self.frame4)
        self.startFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.startFrame_lineEdit.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startFrame_lineEdit.setFont(font)
        self.startFrame_lineEdit.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(100,100,100);"))
        self.startFrame_lineEdit.setObjectName(_fromUtf8("startFrame_lineEdit"))
        self.gridLayout_3.addWidget(self.startFrame_lineEdit, 0, 2, 1, 1)
        self.endFrame_lineEdit = QtWidgets.QLineEdit(self.frame4)
        self.endFrame_lineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.endFrame_lineEdit.setMaximumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.endFrame_lineEdit.setFont(font)
        self.endFrame_lineEdit.setStyleSheet(_fromUtf8("color : white;\n"
"background-color: rgb(100,100,100);"))
        self.endFrame_lineEdit.setObjectName(_fromUtf8("endFrame_lineEdit"))
        self.gridLayout_3.addWidget(self.endFrame_lineEdit, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_9.setStyleSheet(_fromUtf8("color : white;"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_8.setStyleSheet(_fromUtf8("color : white;"))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame4, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.frame3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 1, 0, 1, 2)
        self.gridLayout_7.addWidget(self.frame3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame2, 1, 0, 1, 2)
        self.gridLayout_14.addLayout(self.gridLayout_10, 2, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, -1, 15)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color : white;"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.frame5 = QtWidgets.QFrame(self.frame)
        self.frame5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame5.setObjectName(_fromUtf8("frame5"))
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame5)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.sceneGraphTreeWidget = QtWidgets.QTreeWidget(self.frame5)
        self.sceneGraphTreeWidget.setRootIsDecorated(True)
        self.sceneGraphTreeWidget.setHeaderHidden(True)
        self.sceneGraphTreeWidget.setObjectName(_fromUtf8("sceneGraphTreeWidget"))
        self.sceneGraphTreeWidget.setStyleSheet("""
                                                        QTreeWidget { color: white; font: bold 15px;}
                                                        QHeaderView { color: white; font: bold 15px;}
                                                        QCheckBox { color: white; font: bold 15px; }
                                                        """)
        self.sceneGraphTreeWidget.headerItem().setText(0, _fromUtf8("node"))
        self.sceneGraphTreeWidget.headerItem().setText(1, _fromUtf8("version"))
        self.sceneGraphTreeWidget.header().resizeSection(0, 360)
        self.sceneGraphTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.gridLayout_16.addWidget(self.sceneGraphTreeWidget, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame5, 1, 0, 1, 5)
        self.gridLayout.addLayout(self.gridLayout_13, 1, 0, 1, 2)
        self.gridLayout_14.addLayout(self.gridLayout, 2, 0, 1, 2)
        self.gridLayout_11.addWidget(self.frame, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.title_label.setText(_translate("Form", " USD EXPORT 3.0", None))
        # self.mayaVer_comboBox.setItemText(0, _translate("Form", "MAYA 2017", None))
        self.userName_label.setText(_translate("Form", "user:", None))
        # self.label_3.setText(_translate("Form", "SHOW", None))
        # self.allTask_label.setText(_translate("Form", "ALL TASK", None))
        # self.workType_comboBox.setItemText(0, _translate("Form", "shot", None))
        # self.workType_comboBox.setItemText(1, _translate("Form", "asset", None))
        self.label_4.setText(_translate("Form", "EXPORT FILE :", None))
        self.findExportFile_pushButton.setText(_translate("Form", "...", None))
        self.label_6.setText(_translate("Form", "OUT DIR:", None))
        self.findOutDir_pushButton.setText(_translate("Form", "...", None))
        self.label_12.setText(_translate("Form", "   SETTINGS", None))
        self.machineType_comboBox.setItemText(0, _translate("Form", "TRACTOR", None))
        self.machineType_comboBox.setItemText(1, _translate("Form", "LOCAL", None))
        self.doExport_pushButton.setText(_translate("Form", "EXPORT", None))
        self.label_2.setText(_translate("Form", "Post Process", None))
        self.rigVersionUp_checkBox.setText(_translate("Form", "dxRig version up", None))
        self.groom_checkBox.setText(_translate("Form", "groom export", None))
        self.only_groom_checkBox.setText(_translate("Form", "only groom export", None))
        self.label.setText(_translate("Form", "Crowd", None))
        self.only_bake_checkBox.setText(_translate("Form", "only bake export", None))
        self.dontParallelCheckBox.setText(_translate("Form", "don't parallel export", None))
        self.label_10.setText(_translate("Form", "FRAME", None))
        self.label_9.setText(_translate("Form", "STEP :", None))
        self.label_8.setText(_translate("Form", "FRAME :", None))
        self.label_11.setText(_translate("Form", "SceneGraph", None))
